### ISSUE TITLE
express module missing

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#6]
It seems that the `express` module is needed but not included in your `package.json`.
Running the watch option outputs the following error:

```
Wahs-MacBook-Pro:lomath kengz$ ./node_modules/dokker/bin/watch 

/Users/kengz/Google Drive/lomath/node_modules/dokker/node_modules/promise/lib/done.js:10
      throw err;
            ^
module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kengz/Google Drive/lomath/docs/app.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by ghost** [comment]
Yup, there was something missing. Thx!
